name: release
on:
  # Test that it works on pull_request; goreleaser goes into snapshot mode if not a tag.
  pull_request:
  push:
    tags:
      - v*

permissions:
  # goreleaser writes to the releases api
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    env:
      flags: ""

    steps:
      - if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        run: echo "flags=--snapshot" >> $GITHUB_ENV

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch git tags
        run: git fetch --force --tags

      - name: Set up Go
        uses: actions/setup-go@v5.3.0
        with:
          go-version: '1.24'
          cache: true

      - name: Go Release
        uses: goreleaser/goreleaser-action@v6
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          # 'latest', 'nightly', or a semver
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
